name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_for_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target/