name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_for_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release
      - shell: bash
        run: echo "Hello, world!" > hello.txt
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: hello
          path: hello.txt